### ISSUE TITLE
Targeting ES5  does not work

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/experimental-biotope-components#25]
## Expected behavior
I can set the build target to ES5 in the tsconfig and everything works.

## Actual behavior
The webcomponents won't work.

## Steps to reproduce

  1. Set target to ES5
  2. Yarn start
  3. Open the demo

## Specifications

  - Biotope Version:
  - Node Version:
  - Yarn Version:
  - Operating System: OsX
  - Browser & Version: Chrome

**Comment by SheepFromHeaven** [comment]
@tiagomapmarques I pushed to the branch target-es6 

It's still not working, but the errors are gone. This might be a browser issue.
Let's tackle it tomorrow!

**Comment by timomayer** [comment]
maybe thats related to: https://github.com/biotope/biotope-build/issues/129 ?

**Comment by timomayer** [comment]
so is this issue solved with biotope-build 5.4.1?

**Comment by tiagomapmarques** [comment]
Closed by #35
